### PR TITLE
Added custom arguments support

### PR DESCRIPTION
**Pull request by NeoTheFox**

### CODE REVIEW

**Comment by lillelilje** [comment]
Looks nice. I'll give it a spin and merge soon

**Comment by lillelilje** [comment]
Hey, could you make it create the config file if it's not detected? After that I'll merge.
Also there was a comma too much in the imports ;)

**Comment by NeoTheFox** [comment]
Done

**Comment by lillelilje** [comment]
Nice work!
However, I think something is missing...
I'll rework it slightly, mainly making a preferences window where you can edit it instead of having to manually edit the config file.
Would be better for adding options in the future anyways :)

**Comment by lillelilje** [comment]
Implemented on a new shiny dev branch now.

**Comment by NeoTheFox** [comment]
Great, thanks!

**Comment by lillelilje** [comment]
https://github.com/oleerik/comptray/tree/dev

**Pull request merged**
